// examples/react/App.jsx
/**
 * @devify/ui + React — production-ready usage pattern
 *
 * Setup (Vite or CRA):
 *   npm install @devify/ui
 *
 * In main.jsx / index.jsx:
 *   import '@devify/ui';           // register all components
 *   import '@devify/ui/devify.css'; // design tokens
 *
 * TypeScript users: add to vite.config.ts or tsconfig:
 *   "@types/react": { "compilerOptions": { "customElements": "allowAll" } }
 *   or declare module types via a .d.ts file (see gotchas below).
 */

import { useState, useEffect, useRef, useCallback } from 'react';

// ─── Reusable wrapper hooks ────────────────────────────────────────────────────

/**
 * Hook: attach a DOM event listener to a ref and clean it up.
 *
 * GOTCHA: React's synthetic event system does NOT propagate CustomEvents.
 * You MUST use addEventListener on the actual DOM node.
 */
function useCustomEvent(ref, eventName, handler) {
  useEffect(() => {
    const el = ref.current;
    if (!el || !handler) return;
    el.addEventListener(eventName, handler);
    return () => el.removeEventListener(eventName, handler);
  }, [ref, eventName, handler]);
}

/**
 * Hook: sync a boolean attribute on a custom element.
 *
 * GOTCHA: React passes boolean `true` as the string "true", which doesn't
 * match attribute-presence checks in web components. Use this hook instead.
 */
function useBoolAttr(ref, attrName, value) {
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    value ? el.setAttribute(attrName, '') : el.removeAttribute(attrName);
  }, [ref, attrName, value]);
}

// ─── Wrapper components ────────────────────────────────────────────────────────

/**
 * Two-way bound <dvfy-switch> wrapper.
 *
 * @param {{ label: string, checked: boolean, onChange: (value: boolean) => void }} props
 */
export function DvfySwitch({ label, checked, onChange }) {
  const ref = useRef(null);
  useBoolAttr(ref, 'checked', checked);
  useCustomEvent(ref, 'change', useCallback((e) => {
    onChange?.(e.detail?.checked ?? ref.current?.hasAttribute('checked'));
  }, [onChange]));
  return <dvfy-switch ref={ref} label={label} />;
}

/**
 * Controlled <dvfy-input> wrapper.
 *
 * @param {{ label: string, value: string, onInput: (value: string) => void }} props
 */
export function DvfyInput({ label, value, onInput, ...rest }) {
  const ref = useRef(null);

  useCustomEvent(ref, 'input', useCallback((e) => {
    onInput?.(e.target?.value ?? e.detail?.value ?? '');
  }, [onInput]));

  // Keep the underlying <input> value in sync with React state
  useEffect(() => {
    const el = ref.current;
    if (!el || value === undefined) return;
    const inner = el.querySelector('input');
    if (inner && inner.value !== value) inner.value = value;
  }, [value]);

  return <dvfy-input ref={ref} label={label} {...rest} />;
}

/**
 * <dvfy-button> wrapper with boolean attribute handling.
 *
 * @param {{ children, onClick, variant, size, disabled, loading }} props
 */
export function DvfyButton({ children, onClick, variant, size, disabled, loading }) {
  const ref = useRef(null);
  useBoolAttr(ref, 'disabled', disabled);
  useBoolAttr(ref, 'loading', loading);
  useCustomEvent(ref, 'click', onClick);
  return <dvfy-button ref={ref} variant={variant} size={size}>{children}</dvfy-button>;
}

/**
 * <dvfy-tabs> with onTabChange callback.
 *
 * @param {{ children, onTabChange: (label: string) => void }} props
 */
export function DvfyTabs({ children, onTabChange }) {
  const ref = useRef(null);
  useCustomEvent(ref, 'tab-change', useCallback((e) => {
    onTabChange?.(e.detail?.label);
  }, [onTabChange]));
  return <dvfy-tabs ref={ref}>{children}</dvfy-tabs>;
}

// ─── Example usage ─────────────────────────────────────────────────────────────

export default function App() {
  const [notifications, setNotifications] = useState(true);
  const [query, setQuery]                 = useState('');
  const [saving, setSaving]               = useState(false);
  const [activeTab, setActiveTab]         = useState('Overview');

  const handleSave = useCallback(() => {
    setSaving(true);
    setTimeout(() => setSaving(false), 1500);
  }, []);

  return (
    <div style={{ maxWidth: 640, margin: '0 auto', padding: 'var(--dvfy-space-8)' }}>
      <h1>@devify/ui + React</h1>

      {/* Static attributes work without a wrapper */}
      <dvfy-alert variant="info" title="Framework note" style={{ marginBottom: 'var(--dvfy-space-6)' }}>
        Pure display components need no wrapper. Only interactive components
        that emit CustomEvents or use boolean attributes need thin wrappers.
      </dvfy-alert>

      {/* Two-way switch */}
      <DvfySwitch
        label="Enable notifications"
        checked={notifications}
        onChange={setNotifications}
      />
      <p style={{ fontSize: 'var(--dvfy-text-sm)', color: 'var(--dvfy-text-secondary)', marginTop: 'var(--dvfy-space-1)' }}>
        Notifications: {notifications ? 'ON' : 'OFF'}
      </p>

      {/* Controlled input */}
      <DvfyInput
        label="Search"
        value={query}
        onInput={setQuery}
        placeholder="Type to search…"
        style={{ marginTop: 'var(--dvfy-space-4)' }}
      />

      {/* Button with loading state */}
      <DvfyButton
        variant="default"
        loading={saving}
        disabled={saving}
        onClick={handleSave}
        style={{ marginTop: 'var(--dvfy-space-4)' }}
      >
        {saving ? 'Saving…' : 'Save'}
      </DvfyButton>

      {/* Tabs with onTabChange */}
      <DvfyTabs onTabChange={setActiveTab} style={{ marginTop: 'var(--dvfy-space-8)' }}>
        <dvfy-tab label="Overview" active="">
          <p>Overview content. Active tab state: <strong>{activeTab}</strong></p>
        </dvfy-tab>
        <dvfy-tab label="Settings">
          <p>Settings content</p>
        </dvfy-tab>
      </DvfyTabs>

      {/* Display-only components — no wrapper needed */}
      <div style={{ marginTop: 'var(--dvfy-space-6)', display: 'flex', gap: 'var(--dvfy-space-2)' }}>
        <dvfy-badge>Default</dvfy-badge>
        <dvfy-badge variant="success">Success</dvfy-badge>
        <dvfy-badge variant="warning">Warning</dvfy-badge>
      </div>
    </div>
  );
}

// ─── Gotchas summary ───────────────────────────────────────────────────────────
//
// 1. CustomEvents → use addEventListener via useRef, not onClick/onChange.
//    React's synthetic events don't capture bubbling CustomEvents.
//
// 2. Boolean attributes → pass "" (empty string) or use setAttribute/removeAttribute.
//    React converts `disabled={true}` to the string "true", not attribute presence.
//    Pattern: <dvfy-button disabled={isDisabled ? "" : undefined}>
//    Or use the useBoolAttr hook above.
//
// 3. TypeScript → add global JSX type declarations in a dvfy.d.ts file:
//    declare global {
//      namespace JSX {
//        interface IntrinsicElements {
//          'dvfy-button': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> & {
//            variant?: string; size?: string; disabled?: string; loading?: string;
//          };
//          // ... add others as needed
//        }
//      }
//    }
//
// 4. Server-side rendering (Next.js) → custom elements are browser-only.
//    Wrap component usage in a dynamic import with { ssr: false }:
//    const DvfyButton = dynamic(() => import('./DvfyButton'), { ssr: false });
//
// 5. ref on custom elements → React 18 forwards refs to the DOM node directly.
//    No need for forwardRef on these wrappers.

// examples/vue/App.vue
<!--
  @devify/ui + Vue 3 SFC — production-ready usage pattern

  Setup (Vite):
    npm install @devify/ui

  In main.ts:
    import '@devify/ui';
    import '@devify/ui/devify.css';

  In vite.config.ts — declare dvfy-* as custom elements to suppress warnings:
    import { defineConfig } from 'vite'
    import vue from '@vitejs/plugin-vue'

    export default defineConfig({
      plugins: [
        vue({
          template: {
            compilerOptions: {
              isCustomElement: (tag) => tag.startsWith('dvfy-'),
            },
          },
        }),
      ],
    })

  Nuxt users: add to nuxt.config.ts:
    vue: {
      compilerOptions: {
        isCustomElement: (tag) => tag.startsWith('dvfy-'),
      },
    }
    // and wrap client-only code in <ClientOnly> or a .client.vue component
-->

<template>
  <div style="max-width: 640px; margin: 0 auto; padding: var(--dvfy-space-8)">
    <h1>@devify/ui + Vue 3</h1>

    <dvfy-alert variant="info" title="Key patterns" style="margin-bottom: var(--dvfy-space-6)">
      Use <code>:attr="value ? '' : undefined"</code> for boolean attributes.
      Use <code>@event-name</code> for CustomEvents — Vue 3 handles them natively.
    </dvfy-alert>

    <!-- ── Switch ─────────────────────────────────────────────── -->
    <!--
      Boolean attr pattern: bind to "" (adds attribute) or undefined (removes it).
      @change fires on the "change" CustomEvent dispatched by dvfy-switch.
    -->
    <dvfy-switch
      label="Enable notifications"
      :checked="notifications ? '' : undefined"
      @change="notifications = $event.detail?.checked ?? !notifications"
    />
    <p style="font-size: var(--dvfy-text-sm); color: var(--dvfy-text-secondary)">
      Notifications: {{ notifications ? 'ON' : 'OFF' }}
    </p>

    <!-- ── Controlled input ──────────────────────────────────── -->
    <!--
      v-model doesn't bind to custom elements by default.
      Vue 3.4+ supports v-model:value for elements that dispatch
      an "update:value" event — dvfy-input dispatches "input" instead,
      so use the explicit :value + @input pattern.
    -->
    <dvfy-input
      label="Your name"
      :value="name"
      @input="name = $event.target?.value ?? $event.detail?.value ?? ''"
      placeholder="Jane Smith"
      required
      style="margin-top: var(--dvfy-space-4)"
    />

    <!-- ── Checkbox ───────────────────────────────────────────── -->
    <dvfy-checkbox
      label="Accept terms"
      :checked="accepted ? '' : undefined"
      @change="accepted = $event.detail?.checked ?? !accepted"
      style="margin-top: var(--dvfy-space-4)"
    />

    <!-- ── Select ─────────────────────────────────────────────── -->
    <dvfy-select
      label="Priority"
      @change="priority = $event.target?.value"
      style="margin-top: var(--dvfy-space-4)"
    >
      <option value="">Select…</option>
      <option value="low">Low</option>
      <option value="medium">Medium</option>
      <option value="high">High</option>
    </dvfy-select>

    <!-- ── Textarea ───────────────────────────────────────────── -->
    <dvfy-textarea
      label="Notes"
      :value="notes"
      @input="notes = $event.target?.value ?? $event.detail?.value ?? ''"
      placeholder="Optional notes…"
      style="margin-top: var(--dvfy-space-4)"
    />

    <!-- ── Button ─────────────────────────────────────────────── -->
    <!--
      loading and disabled are boolean attrs — use the "" / undefined pattern.
      @click fires the native click event.
    -->
    <dvfy-button
      :disabled="saving ? '' : undefined"
      :loading="saving ? '' : undefined"
      @click="handleSave"
      style="margin-top: var(--dvfy-space-4)"
    >
      {{ saving ? 'Saving…' : 'Save' }}
    </dvfy-button>

    <!-- ── Success message ───────────────────────────────────── -->
    <dvfy-alert
      v-if="saved"
      variant="success"
      title="Saved!"
      dismissible
      style="margin-top: var(--dvfy-space-4)"
    >
      Hello, {{ name }}!
    </dvfy-alert>

    <!-- ── Tabs ───────────────────────────────────────────────── -->
    <!--
      @tab-change fires with detail: { label } when the user clicks a tab.
      Control which tab is active by binding the "active" boolean attr.
    -->
    <dvfy-tabs
      @tab-change="activeTab = $event.detail?.label"
      style="margin-top: var(--dvfy-space-8)"
    >
      <dvfy-tab
        label="Overview"
        :active="activeTab === 'Overview' ? '' : undefined"
      >
        <p>Overview content. Current tab: <strong>{{ activeTab }}</strong></p>
      </dvfy-tab>
      <dvfy-tab
        label="Settings"
        :active="activeTab === 'Settings' ? '' : undefined"
      >
        <p>Settings content.</p>
      </dvfy-tab>
    </dvfy-tabs>

    <!-- ── Display-only components — no special handling ─────── -->
    <div style="margin-top: var(--dvfy-space-6); display: flex; gap: var(--dvfy-space-2); flex-wrap: wrap">
      <dvfy-badge>Default</dvfy-badge>
      <dvfy-badge variant="success">Success</dvfy-badge>
      <dvfy-badge variant="warning">Warning</dvfy-badge>
      <dvfy-badge variant="danger">Danger</dvfy-badge>
    </div>

    <dvfy-accordion style="margin-top: var(--dvfy-space-8)">
      <dvfy-accordion-item label="Vue 3 gotchas" open>
        <ul style="padding-left: var(--dvfy-space-4); font-size: var(--dvfy-text-sm)">
          <li>Add <code>isCustomElement</code> to compiler options</li>
          <li>Boolean attrs: use <code>"" / undefined</code> pattern</li>
          <li>Events: use <code>@event-name</code> — Vue 3 handles CustomEvents natively</li>
          <li>v-model: not supported on custom elements without defineCustomElement</li>
          <li>Nuxt: use &lt;ClientOnly&gt; for SSR — web components are browser-only</li>
        </ul>
      </dvfy-accordion-item>
    </dvfy-accordion>
  </div>
</template>

<script setup>
import { ref } from 'vue';

const notifications = ref(true);
const name          = ref('');
const accepted      = ref(false);
const priority      = ref('');
const notes         = ref('');
const saving        = ref(false);
const saved         = ref(false);
const activeTab     = ref('Overview');

function handleSave() {
  if (!name.value.trim()) return;
  saving.value = true;
  setTimeout(() => {
    saving.value = false;
    saved.value  = true;
  }, 1200);
}
</script>

<!--
  GOTCHAS SUMMARY
  ───────────────
  1. isCustomElement config — required to suppress "unknown component" warnings.
     Without it, Vue tries to resolve dvfy-button as a Vue component and warns.

  2. Boolean attributes — Vue's :disabled="true" sets the attribute to the
     string "true", not an empty-string presence. Web components check attribute
     presence (el.hasAttribute), so pass "" for present, undefined for absent.
     Pattern: :disabled="isDisabled ? '' : undefined"

  3. Events — Vue 3 delegates to addEventListener natively for unknown events,
     so @change, @input, @tab-change, etc. all work out of the box.
     Vue 2 requires .native modifier — not needed in Vue 3.

  4. v-model — custom elements don't implement the Vue v-model contract
     (modelValue prop + update:modelValue event). Use :value + @input explicitly.
     Vue 3.4 adds <component v-model:value> for elements emitting "update:value",
     but dvfy-* components emit "input" / "change" for web-standards compatibility.

  5. Nuxt / SSR — custom elements are browser-only APIs. Wrap in <ClientOnly>
     or use .client.vue components to avoid hydration mismatches.

  6. TypeScript — Vue 3 doesn't type-check unknown HTML elements in templates.
     To get type safety, declare them in a .d.ts file:
       import type { DefineComponent } from 'vue'
       declare module '@vue/runtime-dom' {
         interface HTMLAttributes {
           // shared attrs
           label?: string
           variant?: string
           size?: string
           disabled?: string
           loading?: string
         }
       }
-->
